_common/package: !include "common/package.yaml"

category:     AWS, Cloud
description:  EDSL for AWS CloudFormation, base types to be used by sibling stratosphere-* packages.
github:       mbj/stratosphere
maintainer:   Markus Schirp
name:         stratosphere
stability:    experimental
synopsis:     EDSL for AWS CloudFormation
version:      1.0.0

<<: *defaults

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- README.md

dependencies:
- aeson            >= 2    && < 3
- aeson-pretty     >= 0.8  && < 2.9
- base             >= 4.8  && < 4.22
- bytestring       >= 0.11 && < 0.13
- containers       >= 0.6  && < 0.9
- mono-traversable >= 1.0  && < 2.0
- text             >= 1.1  && < 3.0

library:
  source-dirs:
  - gen
  - src

  exposed-modules:
  - Paths_stratosphere
  - Stratosphere
  - Stratosphere.Check
  - Stratosphere.NamedItem
  - Stratosphere.Output
  - Stratosphere.Parameter
  - Stratosphere.Prelude
  - Stratosphere.Property
  - Stratosphere.Resource
  - Stratosphere.ResourceAttributes.AutoScalingReplacingUpdatePolicy
  - Stratosphere.ResourceAttributes.AutoScalingRollingUpdatePolicy
  - Stratosphere.ResourceAttributes.AutoScalingScheduledActionPolicy
  - Stratosphere.ResourceAttributes.CreationPolicy
  - Stratosphere.ResourceAttributes.ResourceSignal
  - Stratosphere.ResourceAttributes.UpdatePolicy
  - Stratosphere.ResourceProperties
  - Stratosphere.Tag
  - Stratosphere.Template
  - Stratosphere.Value

tests:
  spec:
    main: Spec.hs
    source-dirs:
    - test
    dependencies:
    - base
    - stratosphere
    - sydtest
    - sydtest-discover
