_common/package: !include "common/package.yaml"

name:         stratosphere
version:      1.0.0
synopsis:     EDSL for AWS CloudFormation
description:  EDSL for AWS CloudFormation
category:     AWS, Cloud
maintainer:   Markus Schirp
stability:    experimental
license:      MIT
github:       mbj/stratosphere

<<: *defaults

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- README.md

dependencies:
- aeson            >= 2
- aeson-pretty     >= 0.8
- base             >= 4.8
- bytestring
- containers
- mono-traversable
- text             >= 1.1

library:
  source-dirs:
  - gen
  - src

  exposed-modules:
  - Paths_stratosphere
  - Stratosphere
  - Stratosphere.Check
  - Stratosphere.NamedItem
  - Stratosphere.Output
  - Stratosphere.Parameter
  - Stratosphere.Prelude
  - Stratosphere.Property
  - Stratosphere.Resource
  - Stratosphere.ResourceAttributes.AutoScalingReplacingUpdatePolicy
  - Stratosphere.ResourceAttributes.AutoScalingRollingUpdatePolicy
  - Stratosphere.ResourceAttributes.AutoScalingScheduledActionPolicy
  - Stratosphere.ResourceAttributes.CreationPolicy
  - Stratosphere.ResourceAttributes.ResourceSignal
  - Stratosphere.ResourceAttributes.UpdatePolicy
  - Stratosphere.ResourceProperties
  - Stratosphere.Tag
  - Stratosphere.Template
  - Stratosphere.Value

tests:
  spec:
    main: Spec.hs
    source-dirs:
    - test
    dependencies:
    - base
    - stratosphere
    - sydtest
    - sydtest-discover
