_common/package: !include "../common/package.yaml"

name:         stratosphere-examples
synopsis:     EDSL for AWS CloudFormation - Examples
description:  EDSL for AWS CloudFormation - Examples
category:     AWS, Cloud
maintainer:   Markus Schirp
stability:    experimental
license:      MIT
github:       mbj/stratosphere

<<: *defaults


extra-source-files:
- test_resources/**/*

dependencies:
- base

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - stratosphere
  - stratosphere-autoscaling
  - stratosphere-ec2
  - stratosphere-iam
  - stratosphere-lambda
  - stratosphere-rds
  - stratosphere-s3

executables:
  stratosphere-examples:
    source-dirs: app
    main: Main
    dependencies:
    - stratosphere-examples

tests:
  stratosphere-examples-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - stratosphere
    - stratosphere-examples
    - sydtest
