_common/package: !include "../common/package.yaml"

name:         golden-test
synopsis:     EDSL for AWS CloudFormation - Golden Test
description:  EDSL for AWS CloudFormation - Golden Test
category:     AWS, Cloud
maintainer:   Markus Schirp
stability:    experimental
license:      MIT
github:       mbj/stratosphere

<<: *defaults

tests:
  golden-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tasty
    - tasty-golden
    - tasty-hunit
    - stratosphere
    - stratosphere-autoscaling
    - stratosphere-ec2
