name: CI

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      STACK_YAML: ${{ github.workspace }}/stack-${{ matrix.ghc }}.yaml
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.4', '9.6', '9.8', '9.10', '9.12']
        os:  [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Stack
      run: ci/setup-stack.sh
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles(env.STACK_YAML, format('{0}.lock', env.STACK_YAML)) }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles(env.STACK_YAML, format('{0}.lock', env.STACK_YAML)) }}
          ${{ matrix.os }}-${{ matrix.ghc }}
    - name: Install dependencies
      run: stack build --test --only-dependencies
    - name: Build
      run: stack build --fast --test --no-run-tests
    - name: Run tests
      run: stack build --fast --test
